name: kysion_storage
description: A powerful, flexible, and type-safe local storage solution for Flutter, supporting multiple storage engines and multi-level security encryption.
version: 0.1.0
repository: https://github.com/kysion/kysion-storage-dart.git
homepage: https://github.com/kysion/kysion-storage-dart
issue_tracker: https://github.com/kysion/kysion-storage-dart/issues
documentation: https://github.com/kysion/kysion-storage-dart/wiki

topics:
    - storage
    - cache
    - encryption
    - preferences

platforms:
    android:
    ios:
    linux:
    macos:
    web:
    windows:

environment:
    sdk: '>=2.12.0 <4.0.0'
    flutter: '>=3.29.3'

dependencies:
    flutter:
        sdk: flutter
    shared_preferences: ^2.5.3
    hive_flutter: ^1.1.0
    meta: ^1.16.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0
    mockito: ^5.4.6
    build_runner: ^2.4.15
    coverage: ^1.12.0

# Test coverage configuration
coverage:
    ignore:
        - 'lib/generated/*.dart'
        - 'lib/src/models.dart'
        - 'test/*.mocks.dart'
        - '**/*.g.dart'
        - 'lib/src/generated/**'
